export const routes = {
  loginScreen: "loginScreen",
  signupScreen: "signupScreen",
  forgotScreen: "forgotScreen",
  tabScreen: "tabScreen",
  servicesScreen: "servicesScreen",
  bookingScreen: "bookingScreen",
  notificationScreen: "notificationScreen",
  profileNavigator: "profileNavigator",
  profileScreen: "profileScreen",
  historyScreen: "historyScreen",
  updateProfile: "updateProfileScreen",
  detailScreen: "detailScreen",
  addService: "addService",
  updateService: "updateService",
  mapScreenSingle: "singlemapScreen",
};
